# Generated by Django 5.0.6 on 2024-06-08 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generation', models.IntegerField()),
                ('color', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('generation', models.IntegerField()),
                ('sprite', models.CharField(max_length=200)),
                ('xp', models.IntegerField()),
                ('xp1', models.IntegerField()),
                ('xp2', models.IntegerField()),
                ('xp3', models.IntegerField()),
                ('xp4', models.IntegerField()),
                ('xp5', models.IntegerField()),
                ('xp6', models.IntegerField()),
                ('xp7', models.IntegerField()),
                ('xp8', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameRegion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.game')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.region')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('access', models.IntegerField(default=0)),
                ('game_region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.gameregion')),
            ],
        ),
        migrations.CreateModel(
            name='Wild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probability', models.IntegerField()),
                ('lvlMin', models.IntegerField()),
                ('lvlMax', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.route')),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='games.specie')),
            ],
        ),
    ]
