# Generated by Django 5.0.6 on 2024-06-09 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameregion',
            name='game',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.game'),
        ),
        migrations.AlterField(
            model_name='gameregion',
            name='region',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='games.region'),
        ),
    ]
