# Generated by Django 5.0.6 on 2024-06-15 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_alter_gameregion_game_alter_gameregion_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameregion',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_regions', to='games.game'),
        ),
        migrations.AlterField(
            model_name='gameregion',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='associated_games', to='games.region'),
        ),
        migrations.AlterField(
            model_name='route',
            name='game_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_region', to='games.gameregion'),
        ),
        migrations.AlterField(
            model_name='wild',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilds', to='games.route'),
        ),
        migrations.AlterField(
            model_name='wild',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wilds', to='games.specie'),
        ),
    ]
