# Generated by Django 5.0.6 on 2024-06-19 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_route_game_region_alter_specie_xp_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specie',
            old_name='xp1',
            new_name='xp1_4',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='xp2',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='xp3',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='xp4',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='xp5',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='xp6',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='xp7',
        ),
        migrations.RemoveField(
            model_name='specie',
            name='xp8',
        ),
    ]
